name: Push to Main

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install app dependencies and build
        run: npm install && npm run build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "The Book App v__VERSION__"
          releaseBody: "An application to install read the Rust Book."
          releaseDraft: true
          prerelease: false
